### ISSUE TITLE
No iCloud Calendar login

### ISSUE THREAD

**Issue by ryumaou** [Vaccarini-Lorenzo/iCalObsidianSync#17]
I copied and installed the plugin, per the instructions, and don't see a place to log into the iCloud account.
Here's a screenshot:
![image](https://github.com/Vaccarini-Lorenzo/iCalObsidianSync/assets/371696/1574709a-c2e1-41b5-ae0b-8263f8f72c56)

**Comment by Vaccarini-Lorenzo** [comment]
> I copied and installed the plugin, per the instructions, and don't see a place to log into the iCloud account.
> 
> Here's a screenshot:
> 
> ![image](https://github.com/Vaccarini-Lorenzo/iCalObsidianSync/assets/371696/1574709a-c2e1-41b5-ae0b-8263f8f72c56)
> 
> 

Hi there!
To login just look for "iCal" in the command palette: There's a specific command to do so.

**Comment by ryumaou** [comment]
Ah, I see.  A little counter-intuitive, but for setup, not a big deal.  Unfortunately, I have 2FA enabled and when I tried to use an application specific password, the plugin kicks back an error about logging in.

**Comment by Vaccarini-Lorenzo** [comment]
Thanks for your feedback! I'll think about some more user-friendly interface.
The plugin supports 2FA too, could you describe the error you're getting? You can access the console pressing ```cmd + option + I``` on macOS or ```ctrl + shift + I``` on windows.

**Comment by ryumaou** [comment]
Yeah, I tried the "regular" iCloud credentials, which are also my Apple ID credentials.  I was able to set up application-specific passwords under my Apple ID.

Here's the console errors I got back:
![image](https://github.com/Vaccarini-Lorenzo/iCalObsidianSync/assets/371696/7b4b4de8-8e5d-48da-b9c7-410d0aa35e6a)

**Comment by ryumaou** [comment]
I just tried again and got the prompt on my iPhone for validating the login, but I don't have anywhere to put the 2FA verification code in Obsidian.
![image](https://github.com/Vaccarini-Lorenzo/iCalObsidianSync/assets/371696/fedbc912-556b-49c1-b138-afbaa10f3dad)

**Comment by Vaccarini-Lorenzo** [comment]
The release [1.1.4](https://github.com/Vaccarini-Lorenzo/iCalObsidianSync/releases/tag/1.1.4) should fix this issue. Thanks for your patience

**Comment by ryumaou** [comment]
That did fix it!  I was prompted for the 2FA code which I entered and got a successful login. 
I have another issue with the Full Calendar plugin in the sidebar, but I'll open a separate issue for that.
Thank you!
