### ISSUE TITLE
Full Calendar in sidebar made tiny

### ISSUE THREAD

**Issue by ryumaou** [Vaccarini-Lorenzo/iCalObsidianSync#20]
When I have iCalObsidianSync enabled, the Full Calendar in the sidebar shrinks to be tiny, like so:
![image](https://github.com/Vaccarini-Lorenzo/iCalObsidianSync/assets/371696/92b80ff6-a8ef-49b2-8b29-8f2fb4d46a16)

When I deactivate this plugin the calendar in the sidebar fills the space.  
Could it possibly be a CSS fix?

**Comment by Vaccarini-Lorenzo** [comment]
Thank you for your feedback once again!
It was a CSS issue indeed. Release [1.1.5](https://github.com/Vaccarini-Lorenzo/iCalObsidianSync/releases/tag/1.1.5) should fix the problem.

**Comment by ryumaou** [comment]
Yes!  Fixed!  This is glorious!
